# syntax=docker/dockerfile:1
# Base image pinned to the multi-arch index digest of python:3.11-slim
# (supply-chain baseline, roadmap item 0.3) — the tag stays alongside the
# digest for readability, but the digest is what pulls. Fetched from the
# Docker Hub registry API on 2026-08-22; update the digest when bumping the
# tag.
# ── Stage 1: build wheel ──────────────────────────────────────────────────────
FROM python:3.11-slim@sha256:9c900dea9e8fb7e16277c179b555cc72d29a352dbc33cff48ad5a0412fd5bfc7 AS builder

WORKDIR /build

RUN pip install --no-cache-dir "build==1.2.*"

COPY pyproject.toml README.md ./
COPY src/ src/

RUN python -m build --wheel --outdir /dist


# ── Stage 2: runtime ──────────────────────────────────────────────────────────
FROM python:3.11-slim@sha256:9c900dea9e8fb7e16277c179b555cc72d29a352dbc33cff48ad5a0412fd5bfc7 AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=8000 \
    MANGOMAS_ENV=prod \
    MANGOMAS_LOG__FORMAT=json

# Non-root user — no home dir, no interactive shell
RUN useradd --no-create-home --shell /bin/false mangomas

WORKDIR /app

COPY --from=builder /dist/*.whl /tmp/wheels/
# requirements.lock pins the full transitive runtime closure (generated by
# pip-compile from pyproject.toml — see the lockfile's header). Passed as a
# constraints file so the wheel install resolves to exactly those versions:
# constraints pin, they never add dependencies.
COPY requirements.lock /tmp/requirements.lock

RUN pip install --no-cache-dir -c /tmp/requirements.lock /tmp/wheels/*.whl \
    && rm -rf /tmp/wheels /tmp/requirements.lock

# Create writable data dir for default SQLite path (./data/mangomas.db) and the
# compose-mounted /data volume.  Both are owned by the non-root user.
RUN mkdir -p /app/data /data \
    && chown -R mangomas:mangomas /app /data

USER mangomas

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python -c "import os, urllib.request; urllib.request.urlopen(f'http://127.0.0.1:{os.getenv(\"PORT\", \"8000\")}/healthz')" || exit 1

CMD ["sh", "-c", "exec python -m uvicorn mangomas.api.app:create_app --factory --host 0.0.0.0 --port ${PORT:-8000}"]
