"""Config-default re-exports for tests.

Imported from ``mangomas.config`` so a Settings change cannot silently
desync the suite. The package facade (``tests.constants.__init__``)
re-exports these with the ``X as X`` idiom; ruff PLC0414 is auto-exempt
on ``__init__.py``.
"""

from __future__ import annotations

from mangomas.config import (
    DEFAULT_EMBEDDINGS_BATCH_SIZE,
    DEFAULT_EMBEDDINGS_DEVICE,
    DEFAULT_EMBEDDINGS_MODEL,
    DEFAULT_EMBEDDINGS_PROVIDER,
    DEFAULT_LLM_BASE_URL,
    DEFAULT_LLM_MODEL,
    DEFAULT_LOOP_MAX_STEPS,
    DEFAULT_LOOP_STEP_TIMEOUT,
    DEFAULT_RAG_CHUNK_OVERLAP,
    DEFAULT_RAG_CHUNK_WORDS,
    DEFAULT_SIGNAL_DIR,
    DEFAULT_SIGNAL_ENABLED,
    DEFAULT_SIGNAL_GENAI_SPANS,
    DEFAULT_SIGNAL_HTTP_TIMEOUT_SECONDS,
    DEFAULT_SIGNAL_HTTP_URL,
    DEFAULT_SIGNAL_POLICY_ID,
    DEFAULT_SIGNAL_POLICY_SNAPSHOT_HASH,
    DEFAULT_SIGNAL_POLICY_VERSION,
    DEFAULT_SIGNAL_SCHEMA_VERSION,
    DEFAULT_SUMMARIZE_HISTORY_LIMIT,
    DEFAULT_VECTOR_COLLECTION,
    DEFAULT_VECTOR_PERSIST_DIR,
    DEFAULT_VECTOR_PROVIDER,
    DEFAULT_VECTOR_TOP_K,
)

__all__ = [
    "DEFAULT_EMBEDDINGS_BATCH_SIZE",
    "DEFAULT_EMBEDDINGS_DEVICE",
    "DEFAULT_EMBEDDINGS_MODEL",
    "DEFAULT_EMBEDDINGS_PROVIDER",
    "DEFAULT_LLM_BASE_URL",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_LOOP_MAX_STEPS",
    "DEFAULT_LOOP_STEP_TIMEOUT",
    "DEFAULT_RAG_CHUNK_OVERLAP",
    "DEFAULT_RAG_CHUNK_WORDS",
    "DEFAULT_SIGNAL_DIR",
    "DEFAULT_SIGNAL_ENABLED",
    "DEFAULT_SIGNAL_GENAI_SPANS",
    "DEFAULT_SIGNAL_HTTP_TIMEOUT_SECONDS",
    "DEFAULT_SIGNAL_HTTP_URL",
    "DEFAULT_SIGNAL_POLICY_ID",
    "DEFAULT_SIGNAL_POLICY_SNAPSHOT_HASH",
    "DEFAULT_SIGNAL_POLICY_VERSION",
    "DEFAULT_SIGNAL_SCHEMA_VERSION",
    "DEFAULT_SUMMARIZE_HISTORY_LIMIT",
    "DEFAULT_VECTOR_COLLECTION",
    "DEFAULT_VECTOR_PERSIST_DIR",
    "DEFAULT_VECTOR_PROVIDER",
    "DEFAULT_VECTOR_TOP_K",
]
