"""MAST v3 failure-mode codes (Cemri et al., arXiv:2503.13657).

Fourteen codes, three categories. Injected-failure tests on the shipped
plan-execute-review graph annotate the mode they exercise. Do not invent a
fifteenth "Mango" mode.
"""

from __future__ import annotations

# Specification issues
MAST_FM_DISOBEY_TASK_SPECIFICATION: str = "FM-1.1"
MAST_FM_DISOBEY_ROLE_SPECIFICATION: str = "FM-1.2"
MAST_FM_STEP_REPETITION: str = "FM-1.3"
MAST_FM_LOSS_OF_CONVERSATION_HISTORY: str = "FM-1.4"
MAST_FM_UNAWARE_OF_TERMINATION_CONDITIONS: str = "FM-1.5"

# Inter-agent misalignment
MAST_FM_CONVERSATION_RESET: str = "FM-2.1"
MAST_FM_FAIL_TO_ASK_FOR_CLARIFICATION: str = "FM-2.2"
MAST_FM_TASK_DERAILMENT: str = "FM-2.3"
MAST_FM_INFORMATION_WITHHOLDING: str = "FM-2.4"
MAST_FM_IGNORED_INPUT: str = "FM-2.5"
MAST_FM_REASONING_ACTION_MISMATCH: str = "FM-2.6"

# Task verification
MAST_FM_PREMATURE_TERMINATION: str = "FM-3.1"
MAST_FM_NO_OR_INCOMPLETE_VERIFICATION: str = "FM-3.2"
MAST_FM_INCORRECT_VERIFICATION: str = "FM-3.3"

MAST_FAILURE_MODES: tuple[str, ...] = (
    MAST_FM_DISOBEY_TASK_SPECIFICATION,
    MAST_FM_DISOBEY_ROLE_SPECIFICATION,
    MAST_FM_STEP_REPETITION,
    MAST_FM_LOSS_OF_CONVERSATION_HISTORY,
    MAST_FM_UNAWARE_OF_TERMINATION_CONDITIONS,
    MAST_FM_CONVERSATION_RESET,
    MAST_FM_FAIL_TO_ASK_FOR_CLARIFICATION,
    MAST_FM_TASK_DERAILMENT,
    MAST_FM_INFORMATION_WITHHOLDING,
    MAST_FM_IGNORED_INPUT,
    MAST_FM_REASONING_ACTION_MISMATCH,
    MAST_FM_PREMATURE_TERMINATION,
    MAST_FM_NO_OR_INCOMPLETE_VERIFICATION,
    MAST_FM_INCORRECT_VERIFICATION,
)

MAST_FAILURE_MODE_COUNT: int = 14

__all__ = [
    "MAST_FAILURE_MODES",
    "MAST_FAILURE_MODE_COUNT",
    "MAST_FM_CONVERSATION_RESET",
    "MAST_FM_DISOBEY_ROLE_SPECIFICATION",
    "MAST_FM_DISOBEY_TASK_SPECIFICATION",
    "MAST_FM_FAIL_TO_ASK_FOR_CLARIFICATION",
    "MAST_FM_IGNORED_INPUT",
    "MAST_FM_INCORRECT_VERIFICATION",
    "MAST_FM_INFORMATION_WITHHOLDING",
    "MAST_FM_LOSS_OF_CONVERSATION_HISTORY",
    "MAST_FM_NO_OR_INCOMPLETE_VERIFICATION",
    "MAST_FM_PREMATURE_TERMINATION",
    "MAST_FM_REASONING_ACTION_MISMATCH",
    "MAST_FM_STEP_REPETITION",
    "MAST_FM_TASK_DERAILMENT",
    "MAST_FM_UNAWARE_OF_TERMINATION_CONDITIONS",
]
